---
title: "T-tester"
author: "Håvard Crantz Lorentzen"
date: '2023-02-22'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)
library(ggpubr)
library(dplyr)
library(rstatix)
library(broom)

data1 <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

endring <- data1 %>%
select(id, time, group, weight, bmi, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass,`o2_puls (ml)`,hf_max, rer_max_30sek, bfmax_30sek, `Ve_L/min_max_30sek`,time_to_exhaustion, borg_end,lac, `arbec_%_maksHF`,`arbec_%_o2max`,arbec_mean_o2,arbec_vo2_ml_min, arbec_RER, arbec_HF, one_rm_newton,one_rm_watt,pmax_left,pmax_right,fmax_left,fmax_right) %>%
#Velger variabler
filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>% #filtrer ut droppouts
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = weight:n) %>%
   pivot_wider(names_from = "time",
              values_from = "value")%>%
    filter(!is.na(pre)) %>%
  filter(!is.na(post)) %>% 
  
  mutate(diff = post - pre) %>%
  pivot_longer(names_to = "time",
               values_to = "value",
               cols = pre:post)%>%
  pivot_wider(names_from = variable,
              values_from = value)%>%
   
  
endringFLS <- endring %>%
  filter(group != "kon")
  
endringKON <- endring %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS <- with(endringFLS, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difFLS)

difKON <- with(endringKON, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difKON)

#parret T-test
t_testFLS <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringFLS, paired = TRUE)

t_testKON <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringKON , paired = TRUE)

```

```{r setup, include=FALSE}

endring_pp <- data1 %>%
select(id, time, group, weight, bmi, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass,`o2_puls (ml)`,hf_max, rer_max_30sek, bfmax_30sek, `Ve_L/min_max_30sek`,time_to_exhaustion, borg_end,lac, `arbec_%_maksHF`,`arbec_%_o2max`,arbec_mean_o2,arbec_vo2_ml_min, arbec_RER, arbec_HF, one_rm_newton,one_rm_watt,pmax_left,pmax_right,fmax_left,fmax_right) #Velger variabler
endring_pp %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>% #filtrer ut droppouts
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = weight:n) %>%
   pivot_wider(names_from = "time",
              values_from = "value")%>%
    filter(!is.na(pre)) %>%
  filter(!is.na(post)) %>% 
  
  mutate(diff = post - pre) %>%
  pivot_longer(names_to = "time",
               values_to = "value",
               cols = pre:post)%>%
  pivot_wider(names_from = variable,
              values_from = value)%>%
   
  
endringFLS_pp <- endring_pp %>%
  filter(group != "kon")
  
endringKON_pp <- endring_pp %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_pp <- with(endringFLS_pp, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difFLS_pp)

difKON_pp <- with(endringKON_pp, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difKON_pp)

#parret T-test
t_testFLS_pp <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringFLS_pp, paired = TRUE)

t_testKON_pp <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringKON_pp , paired_pp = TRUE)

```

```{r setup, include=FALSE}

endring_ppm <- data1 %>%
select(id, time, group, weight, bmi, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass,`o2_puls (ml)`,hf_max, rer_max_30sek, bfmax_30sek, `Ve_L/min_max_30sek`,time_to_exhaustion, borg_end,lac, `arbec_%_maksHF`,`arbec_%_o2max`,arbec_mean_o2,arbec_vo2_ml_min, arbec_RER, arbec_HF, one_rm_newton,one_rm_watt,pmax_left,pmax_right,fmax_left,fmax_right) #Velger variabler
endring_ppm %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 014") %>%  #filtrer ut droppouts
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = weight:n) %>%
   pivot_wider(names_from = "time",
              values_from = "value")%>%
    filter(!is.na(pre)) %>%
  filter(!is.na(post)) %>% 
  
  mutate(diff = post - pre) %>%
  pivot_longer(names_to = "time",
               values_to = "value",
               cols = pre:post)%>%
  pivot_wider(names_from = variable,
              values_from = value)%>%
   
  
endringFLS_ppm <- endring_ppm %>%
  filter(group != "kon")
  
endringKON_ppm <- endring_ppm %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_ppm <- with(endringFLS_ppm, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difFLS_ppm)

difKON_ppm <- with(endringKON_ppm, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difKON_ppm)

#parret T-test
t_testFLS_ppm <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringFLS_ppm, paired = TRUE)

t_testKON_ppm <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringKON_ppm, paired = TRUE)
```

```{r setup, include=FALSE}

endring_itt <- data1 %>%
select(id, time, group, weight, bmi, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass,`o2_puls (ml)`,hf_max, rer_max_30sek, bfmax_30sek, `Ve_L/min_max_30sek`,time_to_exhaustion, borg_end,lac, `arbec_%_maksHF`,`arbec_%_o2max`,arbec_mean_o2,arbec_vo2_ml_min, arbec_RER, arbec_HF, one_rm_newton,one_rm_watt,pmax_left,pmax_right,fmax_left,fmax_right) #Velger variabler
endring_itt %>% #filtrer ut droppouts
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = weight:n) %>%
   pivot_wider(names_from = "time",
              values_from = "value") %>%
    filter(!is.na(pre)) %>%
  filter(!is.na(post)) %>% 
  
  mutate(diff = post - pre) %>%
  pivot_longer(names_to = "time",
               values_to = "value",
               cols = pre:post) %>%
  pivot_wider(names_from = variable,
              values_from = value) %>%
   
  
endringFLS_itt <- endring_itt %>%
  filter(group != "kon")
  
endringKON_itt <- endring_itt %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_itt <- with(endringFLS_itt, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difFLS_itt)

difKON_itt <- with(endringKON_itt, vo2max_ml_min_kg_6x5[time == "pre"] - vo2max_ml_min_kg_6x5[time == "post"])

shapiro.test(difKON_itt)

#parret T-test
t_testFLS_itt <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringFLS_itt, paired = TRUE)

t_testKON_itt <- t.test(vo2max_ml_min_kg_6x5 ~ time, data = endringKON_itt , paired = TRUE)
```