---
title: "Endring mellom pre og post"
author: "Håvard Crantz Lorentzen"
date: "2023-03-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r itt vo2tabell, include=FALSE}

library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

tabell_vo2_itt <- data %>%
select(id, time, group, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass, o2_puls_ml ,hf_max, rer_max_30sek, bfmax_30sek, Ve_L_min_max_30sek, time_to_exhaustion, borg_end,lac) %>%
  mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(vo2max_ml_min_lm_6x5 = vo2max_ml_min_6x5/lean_mass_kg)%>%
  select(id, time, group, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, vo2max_ml_min_lm_6x5,o2_puls_ml, hf_max, rer_max_30sek, bfmax_30sek, Ve_L_min_max_30sek,time_to_exhaustion, borg_end,lac) %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% 
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = vo2max_ml_min_kg_6x5:n) %>%
  group_by(time, group, variable)%>%
 filter(value != "na") %>%
  summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_"))%>%#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
  mutate(variable = factor(variable, levels = c("n", "vo2max_ml_min_kg_6x5", "vo2max_ml_min_6x5", "vo2max_ml_min_lm_6x5" ,"o2_puls_ml", "hf_max", "rer_max_30sek", "bfmax_30sek", "Ve_L_min_max_30sek", "time_to_exhaustion", "borg_end", "lac"), 
              labels = c("Antall", "vo2maks (ml/min/kg)", "vo2maks (ml/min)", "vo2maks (ml/min/m.m)", "o2 puls (ml)", "Maks puls", "Maks RER", "Maks pustefrekvens", "Maks ventialsjon (L/min)", "Tid til utmattelse (s)", "Borg ved Vo2maks", "Laktat"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
  set_header_labels(variable = "",
                     fls_pre= "Pre", 
                     fls_post = "Post",
                     kon_pre = "Pre", 
                     kon_post = "Post") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Frisklivssentral", "Frisklivssentral", "Kontroll", "Kontroll")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør avstander like
  print()


# NA på 14010 HFmax og HFpuls - HFmaks ved post ble satt som hfmaks på pre.
# 11716 har ikke lean mass - variabel ble filtrert ut hos deltager.


```

```{r pp vo2tabell, include=FALSE}

tabell_vo2_pp <- data %>%
select(id, time, group, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass,o2_puls_ml, hf_max, rer_max_30sek, bfmax_30sek, Ve_L_min_max_30sek,time_to_exhaustion, borg_end,lac) %>%
  mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(vo2max_ml_min_lm_6x5 = vo2max_ml_min_6x5/lean_mass_kg)%>%
  select(id, time, group, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, vo2max_ml_min_lm_6x5,o2_puls_ml, hf_max, rer_max_30sek, bfmax_30sek, Ve_L_min_max_30sek, time_to_exhaustion, borg_end,lac) %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% 
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = vo2max_ml_min_kg_6x5:n) %>%
  group_by(time, group, variable)%>%
  filter(value != "na") %>%
  summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_"))%>%#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
  mutate(variable = factor(variable, levels = c("n", "vo2max_ml_min_kg_6x5", "vo2max_ml_min_6x5", "vo2max_ml_min_lm_6x5" ,"o2_puls_ml", "hf_max", "rer_max_30sek", "bfmax_30sek", "Ve_L_min_max_30sek", "time_to_exhaustion", "borg_end", "lac"), 
              labels = c("Antall", "vo2maks (ml/min/kg)", "vo2maks (ml/min)", "vo2maks (ml/min/m.m)", "o2 puls (ml)", "Maks puls", "Maks RER", "Maks pustefrekvens", "Maks ventialsjon (L/min)", "Tid til utmattelse (s)", "Borg ved Vo2maks", "Laktat"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
  set_header_labels(variable = "",
                     fls_pre= "Pre", 
                     fls_post = "Post",
                     kon_pre = "Pre", 
                     kon_post = "Post") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Frisklivssentral", "Frisklivssentral", "Kontroll", "Kontroll")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør avstander like
  print()


# NA på 14010 HFmax og HFpuls - HFmaks ved post ble satt som hfmaks på pre.
# 11716 har ikke lean mass - variabel ble filtrert ut hos deltager.
```

```{r ppm vo2tabell, include=FALSE}

tabell_vo2_ppm <- data %>%
select(id, time, group, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, lean_mass,o2_puls_ml,hf_max, rer_max_30sek, bfmax_30sek, Ve_L_min_max_30sek,time_to_exhaustion, borg_end,lac) %>%
  mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(vo2max_ml_min_lm_6x5 = vo2max_ml_min_6x5/lean_mass_kg)%>%
  select(id, time, group, vo2max_ml_min_kg_6x5,vo2max_ml_min_6x5, vo2max_ml_min_lm_6x5,o2_puls_ml, hf_max, rer_max_30sek, bfmax_30sek, Ve_L_min_max_30sek, time_to_exhaustion, borg_end,lac) %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% 
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = vo2max_ml_min_kg_6x5:n) %>%
  group_by(time, group, variable)%>%
   filter(value != "na") %>%
  summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_"))%>%#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
  mutate(variable = factor(variable, levels = c("n", "vo2max_ml_min_kg_6x5", "vo2max_ml_min_6x5", "vo2max_ml_min_lm_6x5" ,"o2_puls_ml", "hf_max", "rer_max_30sek", "bfmax_30sek", "Ve_L_min_max_30sek", "time_to_exhaustion", "borg_end", "lac"), 
              labels = c("Antall", "vo2maks (ml/min/kg)", "vo2maks (ml/min)", "vo2maks (ml/min/m.m)", "o2 puls (ml)", "Maks puls", "Maks RER", "Maks pustefrekvens", "Maks ventialsjon (ml)", "Tid til utmattelse (s)", "Borg ved Vo2maks", "Laktat"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
  set_header_labels(variable = "",
                     fls_pre= "Pre", 
                     fls_post = "Post",
                     kon_pre = "Pre", 
                     kon_post = "Post") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Frisklivssentral", "Frisklivssentral", "Kontroll", "Kontroll")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør avstander like
  print()


# NA på 14010 HFmax og HFpuls - HFmaks ved post ble satt som hfmaks på pre.
# 11716 har ikke lean mass - variabel ble filtrert ut hos deltager.
```
