---
title: "t-tester styrke"
author: "Håvard Crantz Lorentzen"
date: "2023-03-20"
output: html_document
---

Denne filen innholder tre kodebolker. Alle tre bunner ut i parede t-tester for å se 
på ending innad i Frikslivsgruppen og kontrollgruppen i variabler tilknyttet styrke. 
Det er også test for normalitet. kodebolkene er i rekkefølgen
ITT (intention to treat), pp (per protokoll 2 treningner), ppm (modifisert pp, 1 trening) 

```{r parra t-test PP, include=FALSE}

library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)
library(ggpubr)
library(dplyr)
library(rstatix)
library(broom)



data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

styrke_itt <- data %>%
select(id, time, group, chair_stand_test, one_rm_newton, one_rm_watt, fmax_left, fmax_right, pmax_left, pmax_right) %>% # velgerrelevante variabler
   mutate(fmax = (fmax_right + fmax_left)/2) %>%
  mutate(pmax = (pmax_right + pmax_left)/2) %>%
  select(-fmax_left, -fmax_right, -pmax_left, -pmax_right ) %>%
#Velger variabler
group_by(time,group) %>% # gruitterer etter tid og FLS/kontroll 
  print()

StyrkeFLS_itt <- styrke_itt %>%
  filter(group != "kon")
  
StyrkeKON_itt <- styrke_itt %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_stol_itt <- with(styrke_itt, chair_stand_test[time == "pre"] - chair_stand_test[time == "post"])
shapiro.test(difFLS_stol_itt)

difFLS_rmn_itt <- with(styrke_itt, one_rm_newton[time == "pre"] - one_rm_newton[time == "post"])
shapiro.test(difFLS_rmn_itt)

difFLS_rmw_itt <- with(styrke_itt, one_rm_watt[time == "pre"] - one_rm_watt[time == "post"])
shapiro.test(difFLS_rmw_itt)

difFLS_fmax_itt <- with(styrke_itt, fmax[time == "pre"] - fmax[time == "post"])
shapiro.test(difFLS_fmax_itt)

difFLS_pmax_itt <- with(styrke_itt, pmax[time == "pre"] - pmax[time == "post"])
shapiro.test(difFLS_pmax_itt)



difKON_stol_itt <- with(styrke_itt, chair_stand_test[time == "pre"] - chair_stand_test[time == "post"])
shapiro.test(difKON_stol_itt)

difKON_rmn_itt <- with(styrke_itt, one_rm_newton[time == "pre"] - one_rm_newton[time == "post"])
shapiro.test(difKON_rmn_itt)

difKON_rmw_itt <- with(styrke_itt, one_rm_watt[time == "pre"] - one_rm_watt[time == "post"])
shapiro.test(difKON_rmw_itt)

difKON_fmax_itt <- with(styrke_itt, fmax[time == "pre"] - fmax[time == "post"])
shapiro.test(difKON_fmax_itt)

difKON_pmax_itt <- with(styrke_itt, pmax[time == "pre"] - pmax[time == "post"])
shapiro.test(difKON_pmax_itt)

#parret T-test
t_testFLS_stol_itt <- t.test(chair_stand_test ~ time, data = StyrkeFLS_itt, paired = TRUE)
t_testFLS_rmn_itt <- t.test(one_rm_newton ~ time, data = StyrkeFLS_itt, paired = TRUE)
t_testFLS_rmw_itt <- t.test(one_rm_watt ~ time, data = StyrkeFLS_itt, paired = TRUE)
t_testFLS_fmax_itt <- t.test(fmax ~ time, data = StyrkeFLS_itt, paired = TRUE)
t_testFLS_pmax_itt <- t.test(pmax ~ time, data = StyrkeFLS_itt, paired = TRUE)


t_testKON_stol_itt <- t.test(chair_stand_test ~ time, data = StyrkeKON_itt, paired = TRUE)
t_testKON_rmn_itt <- t.test(one_rm_newton ~ time, data = StyrkeKON_itt, paired = TRUE)
t_testKON_rmw_itt <- t.test(one_rm_watt ~ time, data = StyrkeKON_itt, paired = TRUE)
t_testKON_fmax_itt <- t.test(fmax ~ time, data = StyrkeKON_itt, paired = TRUE)
t_testKON_pmax_itt <- t.test(pmax ~ time, data = StyrkeKON_itt, paired = TRUE)


t_testFLS_stol_itt
t_testFLS_rmn_itt
t_testFLS_rmw_itt
t_testFLS_fmax_itt
t_testFLS_pmax_itt

t_testKON_stol_itt
t_testKON_rmn_itt
t_testKON_rmw_itt
t_testKON_fmax_itt
t_testKON_pmax_itt
```

```{r parra t-test pp , include=FALSE}

styrke_pp <- data %>%
select(id, time, group, chair_stand_test, one_rm_newton, one_rm_watt, fmax_left, fmax_right, pmax_left, pmax_right) %>% # velgerrelevante variabler
   mutate(fmax = (fmax_right + fmax_left)/2) %>%
  mutate(pmax = (pmax_right + pmax_left)/2) %>%
  select(-fmax_left, -fmax_right, -pmax_left, -pmax_right ) %>%
   filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
#Velger variabler
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  print()

StyrkeFLS_pp <- styrke_pp %>%
  filter(group != "kon")
  
StyrkeKON_pp <- styrke_pp %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_stol_pp <- with(styrke_pp, chair_stand_test[time == "pre"] - chair_stand_test[time == "post"])
shapiro.test(difFLS_stol_pp)

difFLS_rmn_pp <- with(styrke_pp, one_rm_newton[time == "pre"] - one_rm_newton[time == "post"])
shapiro.test(difFLS_rmn_pp)

difFLS_rmw_pp <- with(styrke_pp, one_rm_watt[time == "pre"] - one_rm_watt[time == "post"])
shapiro.test(difFLS_rmw_pp)

difFLS_fmax_pp <- with(styrke_pp, fmax[time == "pre"] - fmax[time == "post"])
shapiro.test(difFLS_fmax_pp)

difFLS_pmax_pp <- with(styrke_pp, pmax[time == "pre"] - pmax[time == "post"])
shapiro.test(difFLS_pmax_pp)



difKON_stol_pp <- with(styrke_pp, chair_stand_test[time == "pre"] - chair_stand_test[time == "post"])
shapiro.test(difKON_stol_pp)

difKON_rmn_pp <- with(styrke_pp, one_rm_newton[time == "pre"] - one_rm_newton[time == "post"])
shapiro.test(difKON_rmn_pp)

difKON_rmw_pp <- with(styrke_pp, one_rm_watt[time == "pre"] - one_rm_watt[time == "post"])
shapiro.test(difKON_rmw_pp)

difKON_fmax_pp <- with(styrke_pp, fmax[time == "pre"] - fmax[time == "post"])
shapiro.test(difKON_fmax_pp)

difKON_pmax_pp <- with(styrke_pp, pmax[time == "pre"] - pmax[time == "post"])
shapiro.test(difKON_pmax_pp)

#parret T-test
t_testFLS_stol_pp <- t.test(chair_stand_test ~ time, data = StyrkeFLS_pp, paired = TRUE)
t_testFLS_rmn_pp <- t.test(one_rm_newton ~ time, data = StyrkeFLS_pp, paired = TRUE)
t_testFLS_rmw_pp <- t.test(one_rm_watt ~ time, data = StyrkeFLS_pp, paired = TRUE)
t_testFLS_fmax_pp <- t.test(fmax ~ time, data = StyrkeFLS_pp, paired = TRUE)
t_testFLS_pmax_pp <- t.test(pmax ~ time, data = StyrkeFLS_pp, paired = TRUE)


t_testKON_stol_pp <- t.test(chair_stand_test ~ time, data = StyrkeKON_pp, paired = TRUE)
t_testKON_rmn_pp <- t.test(one_rm_newton ~ time, data = StyrkeKON_pp, paired = TRUE)
t_testKON_rmw_pp <- t.test(one_rm_watt ~ time, data = StyrkeKON_pp, paired = TRUE)
t_testKON_fmax_pp <- t.test(fmax ~ time, data = StyrkeKON_pp, paired = TRUE)
t_testKON_pmax_pp <- t.test(pmax ~ time, data = StyrkeKON_pp, paired = TRUE)


t_testFLS_stol_pp
t_testFLS_rmn_pp
t_testFLS_rmw_pp
t_testFLS_fmax_pp
t_testFLS_pmax_pp



t_testKON_stol_pp
t_testKON_rmn_pp
t_testKON_rmw_pp
t_testKON_fmax_pp
t_testKON_pmax_pp
```

```{r parra t-test ppm, include=FALSE}
styrke_ppm <- data %>%
select(id, time, group, chair_stand_test, one_rm_newton, one_rm_watt, fmax_left, fmax_right, pmax_left, pmax_right) %>% # velgerrelevante variabler
   mutate(fmax = (fmax_right + fmax_left)/2) %>%
  mutate(pmax = (pmax_right + pmax_left)/2) %>%
  select(-fmax_left, -fmax_right, -pmax_left, -pmax_right ) %>%
#Velger variabler
   filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
group_by(time,group) %>% # gruppmerer etter tid og FLS/kontroll 
  print()

StyrkeFLS_ppm <- styrke_ppm %>%
  filter(group != "kon")
  
StyrkeKON_ppm <- styrke_ppm %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_stol_ppm <- with(styrke_ppm, chair_stand_test[time == "pre"] - chair_stand_test[time == "post"])
shapiro.test(difFLS_stol_ppm)

difFLS_rmn_ppm <- with(styrke_ppm, one_rm_newton[time == "pre"] - one_rm_newton[time == "post"])
shapiro.test(difFLS_rmn_ppm)

difFLS_rmw_ppm <- with(styrke_ppm, one_rm_watt[time == "pre"] - one_rm_watt[time == "post"])
shapiro.test(difFLS_rmw_ppm)

difFLS_fmax_ppm <- with(styrke_ppm, fmax[time == "pre"] - fmax[time == "post"])
shapiro.test(difFLS_fmax_ppm)

difFLS_pmax_ppm <- with(styrke_ppm, pmax[time == "pre"] - pmax[time == "post"])
shapiro.test(difFLS_pmax_ppm)



difKON_stol_ppm <- with(styrke_ppm, chair_stand_test[time == "pre"] - chair_stand_test[time == "post"])
shapiro.test(difKON_stol_ppm)

difKON_rmn_ppm <- with(styrke_ppm, one_rm_newton[time == "pre"] - one_rm_newton[time == "post"])
shapiro.test(difKON_rmn_ppm)

difKON_rmw_ppm <- with(styrke_ppm, one_rm_watt[time == "pre"] - one_rm_watt[time == "post"])
shapiro.test(difKON_rmw_ppm)

difKON_fmax_ppm <- with(styrke_ppm, fmax[time == "pre"] - fmax[time == "post"])
shapiro.test(difKON_fmax_ppm)

difKON_pmax_ppm <- with(styrke_ppm, pmax[time == "pre"] - pmax[time == "post"])
shapiro.test(difKON_pmax_ppm)

#parret T-test
t_testFLS_stol_ppm <- t.test(chair_stand_test ~ time, data = StyrkeFLS_ppm, paired = TRUE)
t_testFLS_rmn_ppm <- t.test(one_rm_newton ~ time, data = StyrkeFLS_ppm, paired = TRUE)
t_testFLS_rmw_ppm <- t.test(one_rm_watt ~ time, data = StyrkeFLS_ppm, paired = TRUE)
t_testFLS_fmax_ppm <- t.test(fmax ~ time, data = StyrkeFLS_ppm, paired = TRUE)
t_testFLS_pmax_ppm <- t.test(pmax ~ time, data = StyrkeFLS_ppm, paired = TRUE)


t_testKON_stol_ppm <- t.test(chair_stand_test ~ time, data = StyrkeKON_ppm, paired = TRUE)
t_testKON_rmn_ppm <- t.test(one_rm_newton ~ time, data = StyrkeKON_ppm, paired = TRUE)
t_testKON_rmw_ppm <- t.test(one_rm_watt ~ time, data = StyrkeKON_ppm, paired = TRUE)
t_testKON_fmax_ppm <- t.test(fmax ~ time, data = StyrkeKON_ppm, paired = TRUE)
t_testKON_pmax_ppm <- t.test(pmax ~ time, data = StyrkeKON_ppm, paired = TRUE)


t_testFLS_stol_ppm
t_testFLS_rmn_ppm
t_testFLS_rmw_ppm
t_testFLS_fmax_ppm
t_testFLS_pmax_ppm



t_testKON_stol_ppm
t_testKON_rmn_ppm
t_testKON_rmw_ppm
t_testKON_fmax_ppm
t_testKON_pmax_ppm

```
