---
title: "Styrke_tabell"
author: "Håvard Crantz Lorentzen"
date: "2023-03-20"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA")

tabell_styrke_itt <- data %>%
  select(id, time, group, chair_stand_test, one_rm_newton, one_rm_watt, fmax_left, fmax_right, pmax_left, pmax_right) %>% # velgerrelevante variabler
   mutate(fmax = (fmax_right + fmax_left)/2) %>%
  mutate(pmax = (pmax_right + pmax_left)/2) %>%
  select(-fmax_left, -fmax_right, -pmax_left, -pmax_right ) %>%
  group_by(time,group) %>% # grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% 
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = chair_stand_test:n) %>%
  group_by(time, group, variable)%>%
  filter(value != "na") %>%
  summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_"))%>%#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
  mutate(variable = factor(variable, levels = c("n", "chair_stand_test", "one_rm_newton", "one_rm_watt", "fmax", "pmax"), 
              labels = c("Antall", "Chair stand test", "1 RM (Nm)", "1 RM (Watt)", "Fmax (N)", "Pmax (Watt)"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
  set_header_labels(variable = "",
                     fls_pre= "Pre", 
                     fls_post = "Post",
                     kon_pre = "Pre", 
                     kon_post = "Post") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Frisklivssentral", "Frisklivssentral", "Kontroll", "Kontroll")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør avstander like
 
  print()
  # filtrerer verdier fra pretest
   flextable::save_as_docx(path = "kropp.docx")
```


```{r setup, include=FALSE}

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA")

tabell_styrke_pp <- data %>%
  select(id, time, group, chair_stand_test, one_rm_newton, one_rm_watt, fmax_left, fmax_right, pmax_left, pmax_right) %>% # velgerrelevante variabler
   mutate(fmax = (fmax_right + fmax_left)/2) %>%
  mutate(pmax = (pmax_right + pmax_left)/2) %>%
  select(-fmax_left, -fmax_right, -pmax_left, -pmax_right ) %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
  group_by(time,group) %>% # grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% 
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = chair_stand_test:n) %>%
  group_by(time, group, variable)%>%
  filter(value != "na") %>%
  summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_"))%>%#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
  mutate(variable = factor(variable, levels = c("n", "chair_stand_test", "one_rm_newton", "one_rm_watt", "fmax", "pmax"), 
              labels = c("Antall", "Chair stand test", "1 RM (Nm)", "1 RM (Watt)", "Fmax (N)", "Pmax (Watt)"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
  set_header_labels(variable = "",
                     fls_pre= "Pre", 
                     fls_post = "Post",
                     kon_pre = "Pre", 
                     kon_post = "Post") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Frisklivssentral", "Frisklivssentral", "Kontroll", "Kontroll")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør avstander like
 
  print()
  # filtrerer verdier fra pretest
   flextable::save_as_docx(path = "kropp.docx")
```

```{r setup, include=FALSE}
data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA")

tabell_styrke_ppm <- data %>%
  select(id, time, group, chair_stand_test, one_rm_newton, one_rm_watt, fmax_left, fmax_right, pmax_left, pmax_right) %>% # velgerrelevante variabler
   mutate(fmax = (fmax_right + fmax_left)/2) %>%
  mutate(pmax = (pmax_right + pmax_left)/2) %>%
  select(-fmax_left, -fmax_right, -pmax_left, -pmax_right ) %>%
    filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  group_by(time,group) %>% # grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% 
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = chair_stand_test:n) %>%
  group_by(time, group, variable)%>%
  filter(value != "na") %>%
  summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_"))%>%#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
  mutate(variable = factor(variable, levels = c("n", "chair_stand_test", "one_rm_newton", "one_rm_watt", "fmax", "pmax"), 
              labels = c("Antall", "Chair stand test", "1 RM (Nm)", "1 RM (Watt)", "Fmax (N)", "Pmax (Watt)"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
  set_header_labels(variable = "",
                     fls_pre= "Pre", 
                     fls_post = "Post",
                     kon_pre = "Pre", 
                     kon_post = "Post") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Frisklivssentral", "Frisklivssentral", "Kontroll", "Kontroll")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør avstander like
 
  print()
  # filtrerer verdier fra pretest
   flextable::save_as_docx(path = "kropp.docx")
```