---
title: "Kaloritabell"
author: "Håvard Crantz Lorentzen"
date: '2023-02-22'
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r kaloritabell_itt,results="asis"}
library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)

arb_itt <- read_excel("data/Regning av kaloriforbruk.xlsx")%>%
  select(id, group, time, prosent_hfmaks, prosent_vo2maks, arbec_mean_vo2_ml_min, arbec_mean_RER, kacl_min, kj_min)%>%
 filter(id != "tr031 008") %>%
mutate(arbec_mean_vo2_ml_min = as.numeric(arbec_mean_vo2_ml_min))%>%
  mutate(arbec_mean_RER = as.numeric(arbec_mean_RER)) %>%
mutate(kacl_min = as.numeric(kacl_min)) %>%
mutate(kj_min = as.numeric(kj_min))%>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value",
               cols = prosent_hfmaks:n) %>%# omorgansiserer tallene for å få verdier nedover
 pivot_wider(names_from = "time",
              values_from = "value")%>%
   pivot_longer(names_to = "time", 
               values_to = "value",
               cols = pre:post) %>%
   group_by(group, time, variable) %>% 
  # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
   mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 5),  " (", signif(s, 2), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_")) %>%

#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%#fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
   mutate(variable = factor(variable, levels = c("n", "prosent_hfmaks", "prosent_vo2maks", "arbec_mean_vo2_ml_min", "arbec_mean_RER", "kacl_min", "kj_min"), 
              labels = c("Antall", "Prosent av maks HF", "Prosent av maksVo2",  "Vo2", "RER", "Kacl/min", "KJ/min"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
    set_header_labels(variable = "",
                     fls_pre= "Frisklivssentral", 
                     fls_post = "Frisklivssentral",
                     kon_pre = "Kontroll", 
                     kon_post = "Kontroll") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Pre", "Post", "Pre", "Post")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() # gjør av stander like
   flextable::save_as_docx(path = "arb_itt.docx") #brukes til å lagre til word

```

```{r kaloritabell_pp,results="asis"}

arb_pp <- read_excel("data/Regning av kaloriforbruk.xlsx")%>%
  select(id, group, time, prosent_hfmaks, prosent_vo2maks, arbec_mean_vo2_ml_min, arbec_mean_RER, kacl_min, kj_min)%>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
mutate(arbec_mean_vo2_ml_min = as.numeric(arbec_mean_vo2_ml_min))%>%
  mutate(arbec_mean_RER = as.numeric(arbec_mean_RER)) %>%
mutate(kacl_min = as.numeric(kacl_min)) %>%
mutate(kj_min = as.numeric(kj_min))%>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value",
               cols = prosent_hfmaks:n) %>%# omorgansiserer tallene for å få verdier nedover
 pivot_wider(names_from = "time",
              values_from = "value")%>%
   pivot_longer(names_to = "time", 
               values_to = "value",
               cols = pre:post) %>%
   group_by(group, time, variable) %>% 
  # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
   mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 5),  " (", signif(s, 2), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_")) %>%

#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%#fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
   mutate(variable = factor(variable, levels = c("n", "prosent_hfmaks", "prosent_vo2maks", "arbec_mean_vo2_ml_min", "arbec_mean_RER", "kacl_min", "kj_min"), 
              labels = c("Antall", "Prosent av maks HF", "Prosent av maksVo2",  "Vo2", "RER", "Kacl/min", "KJ/min"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
   set_header_labels(variable = "",
                     fls_pre= "Frisklivssentral", 
                     fls_post = "Frisklivssentral",
                     kon_pre = "Kontroll", 
                     kon_post = "Kontroll") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Pre", "Post", "Pre", "Post")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() # gjør av stander like
  flextable::save_as_docx(path = "arb_pp.docx")
```  
  
  
```{r kaloritabell_ppm,results="asis"}

arb_ppm <- read_excel("data/Regning av kaloriforbruk.xlsx")%>%
  select(id, group, time, prosent_hfmaks, prosent_vo2maks, arbec_mean_vo2_ml_min, arbec_mean_RER, kacl_min, kj_min)%>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
mutate(arbec_mean_vo2_ml_min = as.numeric(arbec_mean_vo2_ml_min))%>%
  mutate(arbec_mean_RER = as.numeric(arbec_mean_RER)) %>%
mutate(kacl_min = as.numeric(kacl_min)) %>%
mutate(kj_min = as.numeric(kj_min))%>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value",
               cols = prosent_hfmaks:n) %>%# omorgansiserer tallene for å få verdier nedover
 pivot_wider(names_from = "time",
              values_from = "value")%>%
   pivot_longer(names_to = "time", 
               values_to = "value",
               cols = pre:post) %>%
   group_by(group, time, variable) %>% 
  # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
   mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 5),  " (", signif(s, 2), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_")) %>%

#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%#fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
   mutate(variable = factor(variable, levels = c("n", "prosent_hfmaks", "prosent_vo2maks", "arbec_mean_vo2_ml_min", "arbec_mean_RER", "kacl_min", "kj_min"), 
              labels = c("Antall", "Prosent av maks HF", "Prosent av maksVo2",  "Vo2", "RER", "Kacl/min", "KJ/min"))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
    set_header_labels(variable = "",
                     fls_pre= "Frisklivssentral", 
                     fls_post = "Frisklivssentral",
                     kon_pre = "Kontroll", 
                     kon_post = "Kontroll") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Pre", "Post", "Pre", "Post")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() # gjør av stander like
  flextable::save_as_docx(path = "arb_ppm.docx")
```

flextable::save_as_docx(path = "Test.docx") #brukes til å lagre til word