---
title: "Deskriptive data"
author: "Håvard Crantz Lorentzen"
date: '2023-02-16'
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r my_table_2, results="asis"}
library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

tabell_1 <- data %>%
select(id,time,group,sex,age, sys, bmi, dia, wc, handgrip, height, weight, vo2max_ml_min_kg_6x5, lean_mass, fat_mass, one_rm_newton) %>% #Velger variabler
drop_na() %>% # fjerner NA
group_by(sex,group) %>% # grupperer etter kjønn og FLS/kontroll
  filter(time == "pre") %>% #filterer ut post for å bare få pre-tester
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = age:n) %>% # omorgansiserer tallene for å få verdier nedover
   group_by(group,sex, variable) %>% # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>% #summerer og får gjennomsnitt og standartdavik på de ulike variablene 
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_sex = paste(group, sex, sep = "_")) %>% #setter "group" og "sex" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -sex) %>% #fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_sex, 
              values_from = ms) %>% # gjør tabellen bredere for å få navn på variabel ved siden av tall
  print()
   mutate(variable = factor(variable, levels = c("n", "age", "weight", "height","bmi", "wc", "handgrip", "sys", "dia","vo2max_ml_min_kg_6x5", "lean_mass", "fat_mass", "one_rm_newton"), 
              labels = c("Antall", "Alder (år)", "Vekt (kg)", "Høyde (cm)","KMI",                            "Livvidde (cm)","Grepsstyrke (kg)",                                                 "Systolisk  blodtrykk (mmHg)",                                                      "Diastolisk blodtrykk (mmHg)", "Vo2maks(ml/kg/min)",                                "Mager masse (gram)", "Fettmasse (gram)",
                         "1RM i benpress (N)" ))) %>% # ordner rekkefølge og norske navn
  select(variable, fls_1, kon_1, fls_2, kon_2) %>% #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
   set_header_labels(variable = "",
                     fls_1= "Frisklivssentral", 
                     kon_1 = "Kontroll",
                     fls_2 = "Frisklivssentral", 
                     kon_2 = "Kontroll") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Kvinner", "Kvinner", "Menn", "Menn")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>% #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 5) %>% #legger til fornote
    autofit() %>% # gjør av stander like
  print()



```


```{r my_table_testing, results="asis"}
library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

tabell_testing <- data %>%
select(id,time,group,sex,age, sys, bmi, dia, wc, handgrip, height, weight, vo2max_ml_min_kg_6x5, lean_mass, fat_mass, one_rm_newton) %>% #Velger variabler
drop_na() %>% # fjerner NA
group_by(sex,group) %>% # grupperer etter kjønn og FLS/kontroll
  filter(time == "pre") %>% #filterer ut post for å bare få pre-tester
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = age:n) %>% # omorgansiserer tallene for å få verdier nedover
   group_by(group,sex, variable) %>%
 # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>% #summerer og får gjennomsnitt og standartdavik på de ulike variablene 
 
  ungroup() %>%#setter "group" og "sex" sammen
  pivot_wider(names_from = c(sex, group), 
              values_from = c(m, s)) %>%
  mutate(fls_m_t = (m_1_fls + m_2_fls)/2, fls_s_t = (s_1_fls + m_2_fls)/2, kon_m_t = (m_1_kon + m_2_kon)/2, kon_s_t = (s_1_kon + s_2_kon)/2) %>%
  
  mutate(ms1_fls = if_else(variable == "n", as.character(m_1_fls), paste0(signif(m_1_fls, 3),  " (", signif(s_1_fls, 3), ")")), 
         ms2_fls = if_else(variable == "n", as.character(m_2_fls), paste0(signif(m_2_fls, 3),  " (", signif(s_2_fls, 3), ")")),
         ms1_kon = if_else(variable == "n", as.character(m_1_kon), paste0(signif(m_1_kon, 3),  " (", signif(s_1_kon, 3), ")")),
         ms2_kon = if_else(variable == "n", as.character(m_2_kon), paste0(signif(m_2_kon, 3),  " (", signif(s_2_kon, 3), ")")),
         mst_fls = if_else(variable == "n", as.character(fls_m_t), paste0(signif(fls_m_t, 3),  " (", signif(fls_s_t, 3), ")")),
         mst_kon = if_else(variable == "n", as.character(kon_m_t), paste0(signif(kon_m_t, 3),  " (", signif(kon_s_t, 3), ")"))) %>%

   select(variable ,mst_fls, mst_kon, ms1_fls, ms1_kon, ms2_fls, ms2_kon) %>%
 #fjerner variablene jeg ikke trenger lenger
   mutate(variable = factor(variable, levels = c("n", "age", "weight", "height","bmi", "wc", "handgrip", "sys", "dia","vo2max_ml_min_kg_6x5", "lean_mass", "fat_mass", "one_rm_newton"), 
              labels = c("Antall", "Alder (år)", "Vekt (kg)", "Høyde (cm)","KMI",                            "Livvidde (cm)","Grepsstyrke (kg)",                                                 "Systolisk  blodtrykk (mmHg)",                                                      "Diastolisk blodtrykk (mmHg)", "Vo2maks(ml/kg/min)",                                "Mager masse (gram)", "Fettmasse (gram)",
                         "1RM i benpress (N)" ))) %>%
  print()

  mutate()# ordner rekkefølge og norske navn #endrer rekkefølge på gruppene
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
   set_header_labels(variable = "",
                     mst_fls= "Frisklivssentral",
                     mst_kon = "kontroll",
                     ms1_fls= "Frisklivssentral", 
                     ms1_kon = "Kontroll",
                     ms2_fls = "Frisklivssentral", 
                     ms2_kon = "Kontroll") %>% # lager overskrifter spesifisert for hver kollonne 
    add_header_row(values = c("", "Kombinert", "Kombinert", "Kvinner", "Kvinner", "Menn", "Menn")) %>%
  merge_at(part = "header", i = 1, j = 2:3) %>%
    merge_at(part = "header", i = 1, j = 4:5) %>%
  #justerer skrifttype
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 7) %>% #legger til fornote
    autofit() %>% # gjør av stander like
  print()



  ```