---
title: "ancova FA"
author: "Håvard Crantz Lorentzen"
date: "2023-04-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(readxl)
library(ggtext)
library(flextable)
library(ggplot2)
library(emmeans)
library(ggpubr)
library(broom)
library(rstatix)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA")

FA_endring1_itt <- data %>%
select(id, time, group, phys_act, phys_work) %>%
   filter(id != "tr031 11716") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = phys_act:phys_work) %>%
  group_by(time, group, variable)%>%
  pivot_wider(names_from = time,
               values_from = value)%>%
  pivot_wider(names_from = variable,
              values_from = c(pre,post))%>%
  ungroup()%>%
  print()

FA_endring1_itt %>% anova_test(post_phys_act ~ group*pre_phys_act)
FA_endring1_itt %>% anova_test(post_phys_work ~ group*pre_phys_work)


#Homogeneity of regression slopes

# Fit the model, the covariate goes first
model_act_itt <- lm(post_phys_act ~ pre_phys_act + group, data = FA_endring1_itt)
model_work_itt <- lm(post_phys_work ~ pre_phys_work + group, data = FA_endring1_itt)


# Inspect the model diagnostic metrics
model.metrics_act_itt <- augment(model_act_itt) %>%
  select(-.hat, -.sigma, -.fitted) # Remove details
  head(model.metrics_act_itt, 22)
  
model.metrics_work_itt <- augment(model_work_itt) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_work_itt, 22)
  

shapiro_test(model.metrics_act_itt$.resid)
shapiro_test(model.metrics_work_itt$.resid)

model.metrics_act_itt %>% levene_test(.resid ~ group)
model.metrics_work_itt %>% levene_test(.resid ~ group)



res.aov_act_itt <- FA_endring1_itt %>% anova_test(post_phys_act ~ pre_phys_act + group)
get_anova_table(res.aov_act_itt)

res.aov_work_itt <- FA_endring1_itt %>% anova_test(post_phys_work ~ pre_phys_work + group)
get_anova_table(res.aov_work_itt)


pwc_act_itt <- FA_endring1_itt%>% 
    emmeans_test(post_phys_act ~ group, covariate = pre_phys_act, p.adjust.method = "bonferroni")
pwc_act_itt
get_emmeans(pwc_act_itt)

pwc_work_itt <- FA_endring1_itt%>% 
emmeans_test(post_phys_work ~ group, covariate = pre_phys_work, p.adjust.method = "bonferroni")



pwc_act_itt$p
pwc_work_itt$p
```

```{r arb ancova pp, include=FALSE}

FA_endring1_pp2 <- data %>%
select(id, time, group, phys_act, phys_work) %>%
    filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
   filter(id != "tr031 11716") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = phys_act:phys_work) %>%
  group_by(time, group, variable)%>%
  pivot_wider(names_from = time,
               values_from = value)%>%
  pivot_wider(names_from = variable,
              values_from = c(pre,post))%>%
  ungroup()%>%
  print()

FA_endring1_pp2 %>% anova_test(post_phys_act ~ group*pre_phys_act)
FA_endring1_pp2 %>% anova_test(post_phys_work ~ group*pre_phys_work)


#Homogeneity of regression slopes

# Fit the model, the covariate goes first
model_act_pp2 <- lm(post_phys_act ~ pre_phys_act + group, data = FA_endring1_pp2)
model_work_pp2 <- lm(post_phys_work ~ pre_phys_work + group, data = FA_endring1_pp2)


# Inspect the model diagnostic metrics
model.metrics_act_pp2 <- augment(model_act_pp2) %>%
  select(-.hat, -.sigma, -.fitted) # Remove details
  head(model.metrics_act_pp2, 22)
  
model.metrics_work_pp2 <- augment(model_work_pp2) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_work_pp2, 22)
  

shapiro_test(model.metrics_act_pp2$.resid)
shapiro_test(model.metrics_work_pp2$.resid)

model.metrics_act_pp2 %>% levene_test(.resid ~ group)
model.metrics_work_pp2 %>% levene_test(.resid ~ group)



res.aov_act_pp2 <- FA_endring1_pp2 %>% anova_test(post_phys_act ~ pre_phys_act + group)
get_anova_table(res.aov_act_pp2)

res.aov_work_pp2 <- FA_endring1_pp2 %>% anova_test(post_phys_work ~ pre_phys_work + group)
get_anova_table(res.aov_work_pp2)


pwc_act_pp2 <- FA_endring1_pp2%>% 
    emmeans_test(post_phys_act ~ group, covariate = pre_phys_act, p.adjust.method = "bonferroni")
pwc_act_pp2
get_emmeans(pwc_act_pp2)

pwc_work_pp2 <- FA_endring1_pp2%>% 
emmeans_test(post_phys_work ~ group, covariate = pre_phys_work, p.adjust.method = "bonferroni")



pwc_act_pp2$p
pwc_work_pp2$p
```

```{r arb ancova ppm, include=FALSE}
FA_endring1_pp1 <- data %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 11716") %>%
select(id, time, group, phys_act, phys_work) %>%

  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = phys_act:phys_work) %>%
  group_by(time, group, variable)%>%
  pivot_wider(names_from = time,
               values_from = value)%>%
  pivot_wider(names_from = variable,
              values_from = c(pre,post))%>%
  ungroup()%>%
  print()

FA_endring1_pp1 %>% anova_test(post_phys_act ~ group*pre_phys_act)
FA_endring1_pp1 %>% anova_test(post_phys_work ~ group*pre_phys_work)


#Homogeneity of regression slopes

# Fit the model, the covariate goes first
model_act_pp1 <- lm(post_phys_act ~ pre_phys_act + group, data = FA_endring1_pp1)
model_work_pp1 <- lm(post_phys_work ~ pre_phys_work + group, data = FA_endring1_pp1)


# Inspect the model diagnostic metrics
model.metrics_act_pp1 <- augment(model_act_pp1) %>%
  select(-.hat, -.sigma, -.fitted) # Remove details
  head(model.metrics_act_pp1, 22)
  
model.metrics_work_pp1 <- augment(model_work_pp1) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_work_pp1, 22)
  

shapiro_test(model.metrics_act_pp1$.resid)
shapiro_test(model.metrics_work_pp1$.resid)

model.metrics_act_pp1 %>% levene_test(.resid ~ group)
model.metrics_work_pp1 %>% levene_test(.resid ~ group)



res.aov_act_pp1 <- FA_endring1_pp1 %>% anova_test(post_phys_act ~ pre_phys_act + group)
get_anova_table(res.aov_act_pp1)

res.aov_work_pp1 <- FA_endring1_pp1 %>% anova_test(post_phys_work ~ pre_phys_work + group)
get_anova_table(res.aov_work_pp1)


pwc_act_pp1 <- FA_endring1_pp1%>% 
    emmeans_test(post_phys_act ~ group, covariate = pre_phys_act, p.adjust.method = "bonferroni")
pwc_act_pp1
get_emmeans(pwc_act_pp1)

pwc_work_pp1 <- FA_endring1_pp1%>% 
emmeans_test(post_phys_work ~ group, covariate = pre_phys_work, p.adjust.method = "bonferroni")



pwc_act_pp1$p
pwc_work_pp1$p
```

