---
title: "Endring FA"
author: "Håvard Crantz Lorentzen"
date: "2023-04-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

Denne filen innholder to kodebolker. Begge beskriver endring i fysisk aktivitetsnivå 
i både frikslisgruppen og kontrollgruppen. Den første bolken viser hvor mye endringen er,
mens den andre viser tall både ved pre-test og ved post-test. Analsyene kommer rekkefølgen
ITT (intention to treat), pp2 (per protokoll 2 treningner), pp1 (per protokoll 1 trening) 
innad i bolkene.

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

 endringFA_pp2 <- data %>%
select(id, time, group, phys_act, phys_work) %>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
   filter(id != "tr031 11716") %>%
#Velger variabler
#filtrer ut droppouts
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = phys_act:n) %>%
  pivot_wider(names_from = "time",
              values_from = "value") %>%
  filter(!is.na(pre)) %>%
  filter(!is.na(post)) %>% 
  mutate(diff = post-pre) %>%
   group_by(group, variable) %>% #legger til variabel i gruppe
summarise(m = mean(diff),
          s = sd(diff), .groups = "drop_last") %>% #summerer og får gjennomsnitt ogstandartdavik på de ulike variablene 
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")"))) %>%
select(-"m", -"s") %>%
  pivot_wider(names_from = group,
              values_from = ms) %>%
  filter(variable != "n")%>%
   mutate(variable = factor(variable, levels = c("phys_act", "phys_work"), 
              labels = c("FA Trening", "FA Arbeid"))) %>% # ordner rekkefølge og norske navn
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
   set_header_labels(variable = "",
                     fls= "Frisklivssentral", 
                     kon = "Kontroll") %>% 
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 3) %>% #legger til fornote
    autofit() %>% # gjør av stander like
  print()

  
  endringFA_pp1 <- data %>%
select(id, time, group, phys_act,phys_work) %>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
    filter(id != "tr031 11716") %>%
     filter(id != "tr031 006") %>%
#Velger variabler
#filtrer ut droppouts
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = phys_act:n) %>%
  pivot_wider(names_from = "time",
              values_from = "value") %>%
  filter(!is.na(pre)) %>%
  filter(!is.na(post)) %>% 
  mutate(diff = post-pre) %>%
   group_by(group, variable) %>% #legger til variabel i gruppe
summarise(m = mean(diff),
          s = sd(diff), .groups = "drop_last") %>% #summerer og får gjennomsnitt ogstandartdavik på de ulike variablene 
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")"))) %>%
select(-"m", -"s") %>%
  pivot_wider(names_from = group,
              values_from = ms) %>%
  filter(variable != "n")%>%
   mutate(variable = factor(variable, levels =c("phys_act", "phys_work"), 
              labels = c("FA Trening", "FA Arbeid"))) %>% # ordner rekkefølge og norske navn
  arrange(variable) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
   set_header_labels(variable = "",
                     fls= "Frisklivssentral", 
                     kon = "Kontroll") %>% 
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 3) %>% #legger til fornote
    autofit() %>% # gjør av stander like
  print()
  
  
  
  endringFA_itt <- data %>%
select(id, time, group, phys_act,phys_work) %>% #Velger variabler
    filter(id != "tr031 11716") %>%
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  mutate(n = n()) %>%
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = phys_act:n) %>%
  pivot_wider(names_from = "time",
              values_from = "value") %>%
  mutate(diff = post-pre) %>%
   group_by(group, variable) %>% #legger til variabel i gruppe
summarise(m = mean(diff),
          s = sd(diff), .groups = "drop_last") %>% #summerer og får gjennomsnitt ogstandartdavik på de ulike variablene 
  mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 3),  " (", signif(s, 3), ")"))) %>%
select(-"m", -"s") %>%
  pivot_wider(names_from = group,
              values_from = ms) %>%
  filter(variable != "n")%>%
   mutate(variable = factor(variable, levels = c("phys_act", "phys_work"), 
              labels = c("FA Trening", "FA Arbeid"))) %>% #ordner rekkefølge på variabelene 
  flextable()  %>%
   set_header_labels(variable = "",
                     fls= "Frisklivssentral", 
                     kon = "Kontroll") %>% 
    add_footer_row(values = "Data er gitt som gjennomsnitt og standardavvik.", colwidths = 3) %>% #legger til fornote
    autofit() %>% # gjør av stander like
  print()
  
```

```{r setup, include=FALSE}

FApre_post_itt <- data %>%
  select(id, time, group, phys_act,phys_work) %>%
  filter(id != "tr031 11716") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value",
               cols = phys_act:n) %>%# omorgansiserer tallene for å få verdier nedover
 pivot_wider(names_from = "time",
              values_from = "value")%>%
   pivot_longer(names_to = "time", 
               values_to = "value",
               cols = pre:post) %>%
   group_by(group, time, variable) %>% 
  # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
   mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 5),  " (", signif(s, 5), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_")) %>%

#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%#fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
 
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
     print()

 
FApre_post_pp2 <- data %>%
  select(id, time, group, phys_act,phys_work) %>%
  filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
  filter(id != "tr031 11716") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value",
               cols = phys_act:n) %>%# omorgansiserer tallene for å få verdier nedover
 pivot_wider(names_from = "time",
              values_from = "value")%>%
   pivot_longer(names_to = "time", 
               values_to = "value",
               cols = pre:post) %>%
   group_by(group, time, variable) %>% 
  # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
   mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 5),  " (", signif(s, 5), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_")) %>%

#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%#fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
 
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
     print()
  


 
FApre_post_pp1 <- data %>%
  select(id, time, group, phys_act,phys_work) %>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 11716") %>%
  filter(id != "tr031 006") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
   
mutate(n = n()) %>% # legger til n for å få antall i hver gruppe
  pivot_longer(names_to = "variable", 
               values_to = "value",
               cols = phys_act:n) %>%# omorgansiserer tallene for å få verdier nedover
 pivot_wider(names_from = "time",
              values_from = "value")%>%
   pivot_longer(names_to = "time", 
               values_to = "value",
               cols = pre:post) %>%
   group_by(group, time, variable) %>% 
  # legger til variabel i gruppe
summarise(m = mean(value),
          s = sd(value), .groups = "drop_last") %>%
   mutate(ms = if_else(variable == "n", as.character(m), paste0(signif(m, 5),  " (", signif(s, 5), ")")), # setter gjennomsnitt og standardavvik (i parentes) sammen og justerer antall desimaler
  group_time = paste(group, time, sep = "_")) %>%

#setter "group" og "tid" sammen
  ungroup() %>% #fjerner gruppering
  select(-m, -s, -group, -time) %>%#fjerner variablene jeg ikke trenger lenger
  pivot_wider(names_from = group_time, 
              values_from = ms) %>%
 
  select(variable, fls_pre, fls_post, kon_pre, kon_post) %>% #endrer rekkefølge på gruppene
     print()

```