---
title: "FA t-test"
author: "Håvard Crantz Lorentzen"
date: "2023-04-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)
library(ggpubr)
library(dplyr)
library(rstatix)
library(broom)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data


FA_endring_itt <- data %>%
select(id, time, group, phys_act, phys_work) %>%
   filter(id != "tr031 11716") %>%
group_by(time,group) %>% # gruitterer etter tid og KON/kontroll 
  print()
   
endring_FA_FLS_itt <- FA_endring_itt %>%
  filter(group != "kon")
  
endring_FA_KON_itt <- FA_endring_itt %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_act_itt <- with(endring_FA_FLS_itt, phys_act[time == "pre"] - phys_act[time == "post"])
shapiro.test(difFLS_act_itt)

difFLS_work_itt <- with(endring_FA_FLS_itt, phys_work[time == "pre"] - phys_work[time == "post"])
shapiro.test(difFLS_work_itt)


difKON_act_itt <- with(endring_FA_KON_itt, phys_act[time == "pre"] - phys_act[time == "post"])
shapiro.test(difKON_act_itt)

difKON_work_itt <- with(endring_FA_KON_itt, phys_work[time == "pre"] - phys_work[time == "post"])
shapiro.test(difKON_work_itt)


#parret T-test Friskliv
t_testFLS_act_itt <- t.test(phys_act ~ time, data = endring_FA_FLS_itt, paired = TRUE)
t_testFLS_work_itt <- t.test(phys_work ~ time, data = endring_FA_FLS_itt, paired = TRUE)


#parret T-test Kontroll
t_testKON_act_itt <- t.test(phys_act ~ time, data = endring_FA_KON_itt, paired = TRUE)
t_testKON_work_itt <- t.test(phys_work ~ time, data = endring_FA_KON_itt, paired = TRUE)



t_testFLS_act_itt
t_testFLS_work_itt


#parret T-test Kontroll
t_testKON_act_itt
t_testKON_work_itt
```


```{r parra t-test pp, include=FALSE}

FA_endring_pp2 <- data %>%
select(id, time, group, phys_act, phys_work) %>%
   filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
   filter(id != "tr031 11716") %>%
group_by(time,group) %>% # gruitterer etter tid og KON/kontroll 
  print()
   
endring_FA_FLS_pp2 <- FA_endring_pp2 %>%
  filter(group != "kon")
  
endring_FA_KON_pp2 <- FA_endring_pp2 %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_act_pp2 <- with(endring_FA_FLS_pp2, phys_act[time == "pre"] - phys_act[time == "post"])
shapiro.test(difFLS_act_pp2)

difFLS_work_pp2 <- with(endring_FA_FLS_pp2, phys_work[time == "pre"] - phys_work[time == "post"])
shapiro.test(difFLS_work_pp2)


difKON_act_pp2 <- with(endring_FA_KON_pp2, phys_act[time == "pre"] - phys_act[time == "post"])
shapiro.test(difKON_act_pp2)

difKON_work_pp2 <- with(endring_FA_KON_pp2, phys_work[time == "pre"] - phys_work[time == "post"])
shapiro.test(difKON_work_pp2)


#parret T-test Friskliv
t_testFLS_act_pp2 <- t.test(phys_act ~ time, data = endring_FA_FLS_pp2, paired = TRUE)
t_testFLS_work_pp2 <- t.test(phys_work ~ time, data = endring_FA_FLS_pp2, paired = TRUE)


#parret T-test Kontroll
t_testKON_act_pp2 <- t.test(phys_act ~ time, data = endring_FA_KON_pp2, paired = TRUE)
t_testKON_work_pp2 <- t.test(phys_work ~ time, data = endring_FA_KON_pp2, paired = TRUE)



t_testFLS_act_pp2
t_testFLS_work_pp2


#parret T-test Kontroll
t_testKON_act_pp2
t_testKON_work_pp2
```


```{r parra t-test ppm, include=FALSE}
FA_endring_pp1 <- data %>%
select(id, time, group, phys_act, phys_work) %>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 11716") %>%
group_by(time,group) %>% # gruitterer etter tid og KON/kontroll 
  print()
   
endring_FA_FLS_pp1 <- FA_endring_pp1 %>%
  filter(group != "kon")
  
endring_FA_KON_pp1 <- FA_endring_pp1 %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_act_pp1 <- with(endring_FA_FLS_pp1, phys_act[time == "pre"] - phys_act[time == "post"])
shapiro.test(difFLS_act_pp1)

difFLS_work_pp1 <- with(endring_FA_FLS_pp1, phys_work[time == "pre"] - phys_work[time == "post"])
shapiro.test(difFLS_work_pp1)


difKON_act_pp1 <- with(endring_FA_KON_pp1, phys_act[time == "pre"] - phys_act[time == "post"])
shapiro.test(difKON_act_pp1)

difKON_work_pp1 <- with(endring_FA_KON_pp1, phys_work[time == "pre"] - phys_work[time == "post"])
shapiro.test(difKON_work_pp1)


#parret T-test Friskliv
t_testFLS_act_pp1 <- t.test(phys_act ~ time, data = endring_FA_FLS_pp1, paired = TRUE)
t_testFLS_work_pp1 <- t.test(phys_work ~ time, data = endring_FA_FLS_pp1, paired = TRUE)


#parret T-test Kontroll
t_testKON_act_pp1 <- t.test(phys_act ~ time, data = endring_FA_KON_pp1, paired = TRUE)
t_testKON_work_pp1 <- t.test(phys_work ~ time, data = endring_FA_KON_pp1, paired = TRUE)



t_testFLS_act_pp1
t_testFLS_work_pp1


#parret T-test Kontroll
t_testKON_act_pp1
t_testKON_work_pp1
```
