---
title: "kroppancova"
author: "Håvard Crantz Lorentzen"
date: "2023-03-20"
output: html_document
editor_options: 
  chunk_output_type: console
---
Denne filen innholder tre kodebolker. Alle tre bunner ut i en ANCOVA-test for å se 
på ending mellom Frikslivsgruppen og kontroll i variabler tilknyttet kropp. Det er også
tester for normalitet, varians og homogenitet. kodebolkene er i rekkefølgen
pp (per protokoll 2 treningner), ppm (modifisert pp, 1 trening) og ITT (intention to treat)

```{r Per protokoll ancova, include=FALSE, results='hide'}
library(tidyverse)
library(knitr)
library(readxl)
library(ggtext)
library(flextable)
library(ggplot2)
library(emmeans)
library(ggpubr)
library(broom)
library(rstatix)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

dexa_pp <- data %>%
select(id, time, group,bmi, wc, lean_mass, fat_mass, total_mass) %>%
 mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(fat_mass_kg = fat_mass/1000) %>%
  mutate(total_mass_kg = total_mass/1000) %>%
  mutate(fatp = fat_mass/total_mass*100) %>%
  select(-lean_mass, -total_mass, -fat_mass) %>%
filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = bmi:fatp) %>%
  group_by(time, group, variable)%>%
  pivot_wider(names_from = time,
               values_from = value)%>%
  pivot_wider(names_from = variable,
              values_from = c(pre,post))%>%
  ungroup()%>%
  print()

ggscatter(dexa_pp, x = "pre_bmi", y = "post_bmi",
  color = "group", add = "reg.line"
  )+
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~"), color = group))

dexa_pp %>% anova_test(post_bmi ~ group*pre_bmi)
dexa_pp %>% anova_test(post_wc ~ group*pre_wc)
dexa_pp %>% anova_test(post_lean_mass_kg ~ group*pre_lean_mass_kg)
dexa_pp %>% anova_test(post_fat_mass_kg ~ group*pre_fat_mass_kg)
dexa_pp %>% anova_test(post_total_mass_kg ~ group*pre_total_mass_kg)
dexa_pp %>% anova_test(post_fatp ~ group*pre_fatp)

#Homogeneity of regression slopes

# Fit the model, the covariate goes first
model_bmi_pp <- lm(post_bmi ~ pre_bmi + group, data = dexa_pp)
model_wc_pp <- lm(post_wc ~ pre_wc + group, data = dexa_pp)
model_lean_pp <- lm(post_lean_mass_kg ~ pre_lean_mass_kg + group, data = dexa_pp)
model_total_pp <- lm(post_total_mass_kg ~ pre_total_mass_kg + group, data = dexa_pp)
model_fat_pp <- lm(post_fat_mass_kg ~ pre_fat_mass_kg + group, data = dexa_pp)
model_fatp_pp <- lm(post_fatp ~ pre_fatp + group, data = dexa_pp)


# Inspect the model diagnostic metrics
model.metrics_bmi_pp <- augment(model_bmi_pp) %>%
  select(-.hat, -.sigma, -.fitted) # Remove details
  head(model.metrics_bmi_pp, 22)
model.metrics_wc_pp <- augment(model_wc_pp) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_wc_pp, 22)
model.metrics_lean_pp <- augment(model_lean_pp) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_lean_pp, 22)
model.metrics_fat_pp <- augment(model_fat_pp) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_fat_pp, 22)
model.metrics_total_pp <- augment(model_total_pp) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_total_pp, 22)
model.metrics_fatp_pp <- augment(model_fatp_pp) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_fatp_pp, 22)

shapiro_test(model.metrics_bmi_pp$.resid)
shapiro_test(model.metrics_wc_pp$.resid)
shapiro_test(model.metrics_lean_pp$.resid)
shapiro_test(model.metrics_fat_pp$.resid)
shapiro_test(model.metrics_total_pp$.resid)
shapiro_test(model.metrics_fatp_pp$.resid)


model.metrics_bmi_pp %>% levene_test(.resid ~ group)
model.metrics_wc_pp %>% levene_test(.resid ~ group)
model.metrics_lean_pp %>% levene_test(.resid ~ group)
model.metrics_fat_pp %>% levene_test(.resid ~ group)
model.metrics_total_pp %>% levene_test(.resid ~ group)
model.metrics_fatp_pp %>% levene_test(.resid ~ group)

model.metrics_bmi_pp %>% 
  filter(abs(.std.resid) > 3) %>%
  as.data.frame()

res.aov_bmi_pp <- dexa_pp %>% anova_test(post_bmi ~ pre_bmi + group)
get_anova_table(res.aov_bmi_pp)

res.aov_wc_pp <- dexa_pp %>% anova_test(post_wc ~ pre_wc + group)
get_anova_table(res.aov_wc_pp)

res.aov_lean_pp <- dexa_pp %>% anova_test(post_lean_mass_kg ~ pre_lean_mass_kg + group)
get_anova_table(res.aov_lean_pp)

res.aov_fat_pp <- dexa_pp %>% anova_test(post_fat_mass_kg ~ pre_fat_mass_kg + group)
get_anova_table(res.aov_fat_pp)

res.aov_total_pp <- dexa_pp %>% anova_test(post_total_mass_kg ~ pre_total_mass_kg + group)
get_anova_table(res.aov_total_pp)

res.aov_fatp_pp <- dexa_pp %>% anova_test(post_fatp ~ pre_fatp + group)
get_anova_table(res.aov_fatp_pp)



pwc_bmi_pp <- dexa_pp %>% 
  emmeans_test(post_bmi ~ group, covariate = pre_bmi, p.adjust.method = "bonferroni")
pwc_bmi_pp
get_emmeans(pwc_bmi_pp)

pwc_wc_pp <- dexa_pp%>% 
emmeans_test(post_wc ~ group, covariate = pre_wc, p.adjust.method = "bonferroni")

pwc_lean_pp <- dexa_pp%>% 
  emmeans_test(post_lean_mass_kg ~ group, covariate = pre_lean_mass_kg, p.adjust.method = "bonferroni")

pwc_fat_pp <- dexa_pp %>% 
  emmeans_test(post_fat_mass_kg ~ group, covariate = pre_fat_mass_kg, p.adjust.method = "bonferroni")

pwc_total_pp <- dexa_pp%>% 
  emmeans_test(post_total_mass_kg ~ group, covariate = pre_total_mass_kg, p.adjust.method = "bonferroni")

pwc_fatp_pp <- dexa_pp%>% 
  emmeans_test(post_fatp ~ group, covariate = pre_fatp, p.adjust.method = "bonferroni")



pwc_bmi_pp$p
pwc_wc_pp$p
pwc_lean_pp$p
pwc_fat_pp$p
pwc_total_pp$p
pwc_fatp_pp$p




pwc_pp <- pwc_lacpp %>% add_xy_position(x = "group", fun = "mean_se")
ggline(get_emmeans(pwc_lacpp), x = "group", y = "emmean") +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) + 
  stat_pvalue_manual(pwc_lacpp, hide.ns = TRUE, tip.length = FALSE) +
  labs(
    subtitle = get_test_label(res.aov_lacpp, detailed = TRUE),
    caption = get_pwc_label(pwc_lacpp))

 vo2_total_pp <- Vo2endring_pp %>%
   mutate(endring = post-pre, prosentvis_endring = (post - pre)/pre * 100) %>%
  group_by(group)%>%
  summarise(mean = mean(endring),
            sd = sd(endring),
            mean_pro = mean(prosentvis_endring),
            sd_pro = sd(prosentvis_endring)) %>%
  print()
 
```

```{r Modifisert per protokoll ancova, include=FALSE, results='hide'}

dexa_ppm <- data %>%
select(id, time, group,bmi, wc, lean_mass, fat_mass, total_mass) %>%
 mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(fat_mass_kg = fat_mass/1000) %>%
  mutate(total_mass_kg = total_mass/1000) %>%
  mutate(fatp = fat_mass/total_mass*100) %>%
  select(-lean_mass, -total_mass, -fat_mass) %>%
 filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  group_by(time,group) %>%# gruppmerer etter tid og FLS/kontroll
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = bmi:fatp) %>%
  group_by(time, group, variable)%>%
  pivot_wider(names_from = time,
               values_from = value)%>%
  pivot_wider(names_from = variable,
              values_from = c(pre,post))%>%
  ungroup()%>%
  print()

ggscatter(Vo2endring_ppm, x = "pre_vo2max_ml_min_kg_6x5", y = "post_vo2max_ml_min_kg_6x5",
  color = "group", add = "reg.line"
  )+
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~"), color = group))



ggscatter(dexa_ppm, x = "pre_bmi", y = "post_bmi",
  color = "group", add = "reg.line"
  )+
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~"), color = group))

dexa_ppm %>% anova_test(post_bmi ~ group*pre_bmi)
dexa_ppm %>% anova_test(post_wc ~ group*pre_wc)
dexa_ppm %>% anova_test(post_lean_mass_kg ~ group*pre_lean_mass_kg)
dexa_ppm %>% anova_test(post_fat_mass_kg ~ group*pre_fat_mass_kg)
dexa_ppm %>% anova_test(post_total_mass_kg ~ group*pre_total_mass_kg)
dexa_ppm %>% anova_test(post_fatp ~ group*pre_fatp)

#Homogeneity of regression slopes

# Fit the model, the covariate goes first
model_bmi_ppm <- lm(post_bmi ~ pre_bmi + group, data = dexa_ppm)
model_wc_ppm <- lm(post_wc ~ pre_wc + group, data = dexa_ppm)
model_lean_ppm <- lm(post_lean_mass_kg ~ pre_lean_mass_kg + group, data = dexa_ppm)
model_total_ppm <- lm(post_total_mass_kg ~ pre_total_mass_kg + group, data = dexa_ppm)
model_fat_ppm <- lm(post_fat_mass_kg ~ pre_fat_mass_kg + group, data = dexa_ppm)
model_fatp_ppm <- lm(post_fatp ~ pre_fatp + group, data = dexa_ppm)


# Inspect the model diagnostic metrics
model.metrics_bmi_ppm <- augment(model_bmi_ppm) %>%
  select(-.hat, -.sigma, -.fitted) # Remove details
  head(model.metrics_bmi_ppm, 22)
model.metrics_wc_ppm <- augment(model_wc_ppm) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_wc_ppm, 22)
model.metrics_lean_ppm <- augment(model_lean_ppm) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_lean_ppm, 22)
model.metrics_fat_ppm <- augment(model_fat_ppm) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_fat_ppm, 22)
model.metrics_total_ppm <- augment(model_total_ppm) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_total_ppm, 22)
model.metrics_fatp_ppm <- augment(model_fatp_ppm) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_fatp_ppm, 22)

shapiro_test(model.metrics_bmi_ppm$.resid)
shapiro_test(model.metrics_wc_ppm$.resid)
shapiro_test(model.metrics_lean_ppm$.resid)
shapiro_test(model.metrics_fat_ppm$.resid)
shapiro_test(model.metrics_total_ppm$.resid)
shapiro_test(model.metrics_fatp_ppm$.resid)


model.metrics_bmi_ppm %>% levene_test(.resid ~ group)
model.metrics_wc_ppm %>% levene_test(.resid ~ group)
model.metrics_lean_ppm %>% levene_test(.resid ~ group)
model.metrics_fat_ppm %>% levene_test(.resid ~ group)
model.metrics_total_ppm %>% levene_test(.resid ~ group)
model.metrics_fatp_ppm %>% levene_test(.resid ~ group)

model.metrics_bmi_ppm %>% 
  filter(abs(.std.resid) > 3) %>%
  as.data.frame()

res.aov_bmi_ppm <- dexa_ppm %>% anova_test(post_bmi ~ pre_bmi + group)
get_anova_table(res.aov_bmi_ppm)

res.aov_wc_ppm <- dexa_ppm %>% anova_test(post_wc ~ pre_wc + group)
get_anova_table(res.aov_wc_ppm)

res.aov_lean_ppm <- dexa_ppm %>% anova_test(post_lean_mass_kg ~ pre_lean_mass_kg + group)
get_anova_table(res.aov_lean_ppm)

res.aov_fat_ppm <- dexa_ppm %>% anova_test(post_fat_mass_kg ~ pre_fat_mass_kg + group)
get_anova_table(res.aov_fat_ppm)

res.aov_total_ppm <- dexa_ppm %>% anova_test(post_total_mass_kg ~ pre_total_mass_kg + group)
get_anova_table(res.aov_total_ppm)

res.aov_fatp_ppm <- dexa_ppm %>% anova_test(post_fatp ~ pre_fatp + group)
get_anova_table(res.aov_fatp_ppm)



pwc_bmi_ppm <- dexa_ppm %>% 
  emmeans_test(post_bmi ~ group, covariate = pre_bmi, p.adjust.method = "bonferroni")
pwc_bmi_ppm
get_emmeans(pwc_bmi_ppm)

pwc_wc_ppm <- dexa_ppm%>% 
emmeans_test(post_wc ~ group, covariate = pre_wc, p.adjust.method = "bonferroni")

pwc_lean_ppm <- dexa_ppm%>% 
  emmeans_test(post_lean_mass_kg ~ group, covariate = pre_lean_mass_kg, p.adjust.method = "bonferroni")

pwc_fat_ppm <- dexa_ppm %>% 
  emmeans_test(post_fat_mass_kg ~ group, covariate = pre_fat_mass_kg, p.adjust.method = "bonferroni")

pwc_total_ppm <- dexa_ppm%>% 
  emmeans_test(post_total_mass_kg ~ group, covariate = pre_total_mass_kg, p.adjust.method = "bonferroni")

pwc_fatp_ppm <- dexa_ppm%>% 
  emmeans_test(post_fatp ~ group, covariate = pre_fatp, p.adjust.method = "bonferroni")



pwc_bmi_ppm$p
pwc_wc_ppm$p
pwc_lean_ppm$p
pwc_fat_ppm$p
pwc_total_ppm$p
pwc_fatp_ppm$p

 
```

```{r Intension to treat ancova, include=FALSE, results='hide'}

dexa_itt <- data %>%
select(id, time, group,bmi, wc, lean_mass, fat_mass, total_mass) %>%
 mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(fat_mass_kg = fat_mass/1000) %>%
  mutate(total_mass_kg = total_mass/1000) %>%
  mutate(fatp = fat_mass/total_mass*100) %>%
  select(-lean_mass, -total_mass, -fat_mass) %>%
  group_by(time,group) %>%# grupperer etter tid og FLS/kontroll
  pivot_longer(names_to = "variable", 
               values_to = "value", 
               cols = bmi:fatp) %>%
  group_by(time, group, variable)%>%
  pivot_wider(names_from = time,
               values_from = value)%>%
  pivot_wider(names_from = variable,
              values_from = c(pre,post))%>%
  ungroup()%>%
  print()



ggscatter(dexa_pp, x = "pre_bmi", y = "post_bmi",
  color = "group", add = "reg.line"
  )+
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~"), color = group))

dexa_itt %>% anova_test(post_bmi ~ group*pre_bmi)
dexa_itt %>% anova_test(post_wc ~ group*pre_wc)
dexa_itt %>% anova_test(post_lean_mass_kg ~ group*pre_lean_mass_kg)
dexa_itt %>% anova_test(post_fat_mass_kg ~ group*pre_fat_mass_kg)
dexa_itt %>% anova_test(post_total_mass_kg ~ group*pre_total_mass_kg)
dexa_itt %>% anova_test(post_fatp ~ group*pre_fatp)

#Homogeneity of regression slopes

# Fit the model, the covariate goes first
model_bmi_itt <- lm(post_bmi ~ pre_bmi + group, data = dexa_itt)
model_wc_itt <- lm(post_wc ~ pre_wc + group, data = dexa_itt)
model_lean_itt <- lm(post_lean_mass_kg ~ pre_lean_mass_kg + group, data = dexa_itt)
model_total_itt <- lm(post_total_mass_kg ~ pre_total_mass_kg + group, data = dexa_itt)
model_fat_itt <- lm(post_fat_mass_kg ~ pre_fat_mass_kg + group, data = dexa_itt)
model_fatp_itt <- lm(post_fatp ~ pre_fatp + group, data = dexa_itt)


# Inspect the model diagnostic metrics
model.metrics_bmi_itt <- augment(model_bmi_itt) %>%
  select(-.hat, -.sigma, -.fitted) # Remove details
  head(model.metrics_bmi_itt, 22)
model.metrics_wc_itt <- augment(model_wc_itt) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_wc_itt, 22)
model.metrics_lean_itt <- augment(model_lean_itt) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_lean_itt, 22)
model.metrics_fat_itt <- augment(model_fat_itt) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_fat_itt, 22)
model.metrics_total_itt <- augment(model_total_itt) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_total_itt, 22)
model.metrics_fatp_itt <- augment(model_fatp_itt) %>%
  select(-.hat, -.sigma, -.fitted) 
  head(model.metrics_fatp_itt, 22)

shapiro_test(model.metrics_bmi_itt$.resid)
shapiro_test(model.metrics_wc_itt$.resid)
shapiro_test(model.metrics_lean_itt$.resid)
shapiro_test(model.metrics_fat_itt$.resid)
shapiro_test(model.metrics_total_itt$.resid)
shapiro_test(model.metrics_fatp_itt$.resid)


model.metrics_bmi_itt %>% levene_test(.resid ~ group)
model.metrics_wc_itt %>% levene_test(.resid ~ group)
model.metrics_lean_itt %>% levene_test(.resid ~ group)
model.metrics_fat_itt %>% levene_test(.resid ~ group)
model.metrics_total_itt %>% levene_test(.resid ~ group)
model.metrics_fatp_itt %>% levene_test(.resid ~ group)

model.metrics_bmi_itt %>% 
  filter(abs(.std.resid) > 3) %>%
  as.data.frame()

res.aov_bmi_itt <- dexa_itt %>% anova_test(post_bmi ~ pre_bmi + group)
get_anova_table(res.aov_bmi_itt)

res.aov_wc_itt <- dexa_itt %>% anova_test(post_wc ~ pre_wc + group)
get_anova_table(res.aov_wc_itt)

res.aov_lean_itt <- dexa_itt %>% anova_test(post_lean_mass_kg ~ pre_lean_mass_kg + group)
get_anova_table(res.aov_lean_itt)

res.aov_fat_itt <- dexa_itt %>% anova_test(post_fat_mass_kg ~ pre_fat_mass_kg + group)
get_anova_table(res.aov_fat_itt)

res.aov_total_itt <- dexa_itt %>% anova_test(post_total_mass_kg ~ pre_total_mass_kg + group)
get_anova_table(res.aov_total_itt)

res.aov_fatp_itt <- dexa_itt %>% anova_test(post_fatp ~ pre_fatp + group)
get_anova_table(res.aov_fatp_itt)



pwc_bmi_itt <- dexa_itt %>% 
  emmeans_test(post_bmi ~ group, covariate = pre_bmi, p.adjust.method = "bonferroni")
pwc_bmi_itt
get_emmeans(pwc_bmi_itt)

pwc_wc_itt <- dexa_itt%>% 
emmeans_test(post_wc ~ group, covariate = pre_wc, p.adjust.method = "bonferroni")

pwc_lean_itt <- dexa_itt%>% 
  emmeans_test(post_lean_mass_kg ~ group, covariate = pre_lean_mass_kg, p.adjust.method = "bonferroni")

pwc_fat_itt <- dexa_itt %>% 
  emmeans_test(post_fat_mass_kg ~ group, covariate = pre_fat_mass_kg, p.adjust.method = "bonferroni")

pwc_total_itt <- dexa_itt%>% 
  emmeans_test(post_total_mass_kg ~ group, covariate = pre_total_mass_kg, p.adjust.method = "bonferroni")

pwc_fatp_itt <- dexa_itt%>% 
  emmeans_test(post_fatp ~ group, covariate = pre_fatp, p.adjust.method = "bonferroni")



pwc_bmi_itt$p
pwc_wc_itt$p
pwc_lean_itt$p
pwc_fat_itt$p
pwc_total_itt$p
pwc_fatp_itt$p

```


```{r soppsummerte ancova pverdier, include=FALSE, results='hide'}

pwc_bmi_pp$p
pwc_wc_pp$p
pwc_lean_pp$p
pwc_fat_pp$p
pwc_total_pp$p
pwc_fatp_pp$p

pwc_bmi_ppm$p
pwc_wc_ppm$p
pwc_lean_ppm$p
pwc_fat_ppm$p
pwc_total_ppm$p
pwc_fatp_ppm$p

pwc_bmi_itt$p
pwc_wc_itt$p
pwc_lean_itt$p
pwc_fat_itt$p
pwc_total_itt$p
pwc_fatp_itt$p

```