---
title: "parra t-test kropp"
author: "Håvard Crantz Lorentzen"
date: "2023-03-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r parra t-test PP, include=FALSE}

library(tidyverse)
library(knitr)
library(flextable)
library(ggplot2)
library(readxl)
library(kableExtra)
library(ggpubr)
library(dplyr)
library(rstatix)
library(broom)

data <- read_excel("data/Revidert_resultatskjema.xlsx", na = "NA") #Henter data

dexa_itt <- data %>%
select(id, time, group,bmi, wc, lean_mass, fat_mass, total_mass) %>% # velgerrelevante variabler
   mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(fat_mass_kg = fat_mass/1000) %>%
  mutate(total_mass_kg = total_mass/1000) %>%
  mutate(fatp = fat_mass/total_mass*100) %>%
  select(-lean_mass, -total_mass, -fat_mass) %>%
#Velger variabler
group_by(time,group) %>% # gruitterer etter tid og FLS/kontroll 
  print()
   
dexaFLS_itt <- dexa_itt %>%
  filter(group != "kon")
  
dexaKON_itt <- dexa_itt %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_bmi_itt <- with(dexaFLS_itt, bmi[time == "pre"] - bmi[time == "post"])
shapiro.test(difFLS_bmi_itt)

difFLS_wc_itt <- with(dexaFLS_itt, wc[time == "pre"] - wc[time == "post"])
shapiro.test(difFLS_wc_itt)

difFLS_lean_itt <- with(dexaFLS_itt, lean_mass_kg[time == "pre"] - lean_mass_kg[time == "post"])
shapiro.test(difFLS_lean_itt)

difFLS_fat_itt <- with(dexaFLS_itt, fat_mass_kg[time == "pre"] - fat_mass_kg[time == "post"])
shapiro.test(difFLS_fat_itt)

difFLS_total_itt <- with(dexaFLS_itt, total_mass_kg[time == "pre"] - total_mass_kg[time == "post"])
shapiro.test(difFLS_total_itt)

difFLS_fatp_itt <- with(dexaFLS_itt, fatp[time == "pre"] - fatp[time == "post"])
shapiro.test(difFLS_fatp_itt)




difKON_bmi_itt <- with(dexaKON_itt, bmi[time == "pre"] - bmi[time == "post"])
shapiro.test(difKON_bmi_itt)

difKON_wc_itt <- with(dexaKON_itt, wc[time == "pre"] - wc[time == "post"])
shapiro.test(difKON_wc_itt)

difKON_lean_itt <- with(dexaKON_itt, lean_mass_kg[time == "pre"] - lean_mass_kg[time == "post"])
shapiro.test(difKON_lean_itt)

difKON_fat_itt <- with(dexaKON_itt, fat_mass_kg[time == "pre"] - fat_mass_kg[time == "post"])
shapiro.test(difKON_fat_itt)

difKON_total_itt <- with(dexaKON_itt, total_mass_kg[time == "pre"] - total_mass_kg[time == "post"])
shapiro.test(difKON_total_itt)

difKON_fatp_itt <- with(dexaKON_itt, fatp[time == "pre"] - fatp[time == "post"])
shapiro.test(difKON_fatp_itt)

#parret T-test
t_testFLS_bmi_itt <- t.test(bmi ~ time, data = dexaFLS_itt, paired = TRUE)
t_testFLS_wc_itt <- t.test(wc ~ time, data = dexaFLS_itt, paired = TRUE)
t_testFLS_lean_itt <- t.test(lean_mass_kg ~ time, data = dexaFLS_itt, paired = TRUE)
t_testFLS_fat_itt <- t.test(fat_mass_kg ~ time, data = dexaFLS_itt, paired = TRUE)
t_testFLS_total_itt <- t.test(total_mass_kg ~ time, data = dexaFLS_itt, paired = TRUE)
t_testFLS_fatp_itt <- t.test(fatp ~ time, data = dexaFLS_itt, paired = TRUE)



t_testKON_bmi_itt <- t.test(bmi ~ time, data = dexaKON_itt, paired = TRUE)
t_testKON_wc_itt <- t.test(wc ~ time, data = dexaKON_itt, paired = TRUE)
t_testKON_lean_itt <- t.test(lean_mass_kg ~ time, data = dexaKON_itt, paired = TRUE)
t_testKON_fat_itt <- t.test(fat_mass_kg ~ time, data = dexaKON_itt, paired = TRUE)
t_testKON_total_itt <- t.test(total_mass_kg ~ time, data = dexaKON_itt, paired = TRUE)
t_testKON_fatp_itt <- t.test(fatp ~ time, data = dexaKON_itt, paired = TRUE)

t_testFLS_bmi_itt
t_testFLS_wc_itt
t_testFLS_lean_itt
t_testFLS_fat_itt
t_testFLS_total_itt
t_testFLS_fatp_itt


t_testKON_bmi_itt
t_testKON_wc_itt
t_testKON_lean_itt
t_testKON_fat_itt
t_testKON_total_itt
t_testKON_fatp_itt
```

```{r parra t-test pp , include=FALSE}

dexa_pp <- data %>%
select(id, time, group,bmi, wc, lean_mass, fat_mass, total_mass) %>% # velgerrelevante variabler
   mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(fat_mass_kg = fat_mass/1000) %>%
  mutate(total_mass_kg = total_mass/1000) %>%
  mutate(fatp = fat_mass/total_mass*100) %>%
  select(-lean_mass, -total_mass, -fat_mass) %>%
#Velger variabler
   filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 014") %>%
  filter(id != "tr031 002") %>%
  filter(id != "tr031 006") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 009") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
  filter(id != "tr031 015") %>%
group_by(time,group) %>% # grupperer etter tid og FLS/kontroll 
  print()
   
dexaFLS_pp <- dexa_pp %>%
  filter(group != "kon")
  
dexaKON_pp <- dexa_pp %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_bmi_pp <- with(dexaFLS_pp, bmi[time == "pre"] - bmi[time == "post"])
shapiro.test(difFLS_bmi_pp)

difFLS_wc_pp <- with(dexaFLS_pp, wc[time == "pre"] - wc[time == "post"])
shapiro.test(difFLS_wc_pp)

difFLS_lean_pp <- with(dexaFLS_pp, lean_mass_kg[time == "pre"] - lean_mass_kg[time == "post"])
shapiro.test(difFLS_lean_pp)

difFLS_fat_pp <- with(dexaFLS_pp, fat_mass_kg[time == "pre"] - fat_mass_kg[time == "post"])
shapiro.test(difFLS_fat_pp)

difFLS_total_pp <- with(dexaFLS_pp, total_mass_kg[time == "pre"] - total_mass_kg[time == "post"])
shapiro.test(difFLS_total_pp)

difFLS_fatp_pp <- with(dexaFLS_pp, fatp[time == "pre"] - fatp[time == "post"])
shapiro.test(difFLS_fatp_pp)




difKON_bmi_pp <- with(dexaKON_pp, bmi[time == "pre"] - bmi[time == "post"])
shapiro.test(difKON_bmi_pp)

difKON_wc_pp <- with(dexaKON_pp, wc[time == "pre"] - wc[time == "post"])
shapiro.test(difKON_wc_pp)

difKON_lean_pp <- with(dexaKON_pp, lean_mass_kg[time == "pre"] - lean_mass_kg[time == "post"])
shapiro.test(difKON_lean_pp)

difKON_fat_pp <- with(dexaKON_pp, fat_mass_kg[time == "pre"] - fat_mass_kg[time == "post"])
shapiro.test(difKON_fat_pp)

difKON_total_pp <- with(dexaKON_pp, total_mass_kg[time == "pre"] - total_mass_kg[time == "post"])
shapiro.test(difKON_total_pp)

difKON_fatp_pp <- with(dexaKON_pp, fatp[time == "pre"] - fatp[time == "post"])
shapiro.test(difKON_fatp_pp)

#parret T-test
t_testFLS_bmi_pp <- t.test(bmi ~ time, data = dexaFLS_pp, paired = TRUE)
t_testFLS_wc_pp <- t.test(wc ~ time, data = dexaFLS_pp, paired = TRUE)
t_testFLS_lean_pp <- t.test(lean_mass_kg ~ time, data = dexaFLS_pp, paired = TRUE)
t_testFLS_fat_pp <- t.test(fat_mass_kg ~ time, data = dexaFLS_pp, paired = TRUE)
t_testFLS_total_pp <- t.test(total_mass_kg ~ time, data = dexaFLS_pp, paired = TRUE)
t_testFLS_fatp_pp <- t.test(fatp ~ time, data = dexaFLS_pp, paired = TRUE)



t_testKON_bmi_pp <- t.test(bmi ~ time, data = dexaKON_pp, paired = TRUE)
t_testKON_wc_pp <- t.test(wc ~ time, data = dexaKON_pp, paired = TRUE)
t_testKON_lean_pp <- t.test(lean_mass_kg ~ time, data = dexaKON_pp, paired = TRUE)
t_testKON_fat_pp <- t.test(fat_mass_kg ~ time, data = dexaKON_pp, paired = TRUE)
t_testKON_total_pp <- t.test(total_mass_kg ~ time, data = dexaKON_pp, paired = TRUE)
t_testKON_fatp_pp <- t.test(fatp ~ time, data = dexaKON_pp, paired = TRUE)

t_testFLS_bmi_pp
t_testFLS_wc_pp
t_testFLS_lean_pp
t_testFLS_fat_pp
t_testFLS_total_pp
t_testFLS_fatp_pp


t_testKON_bmi_pp
t_testKON_wc_pp
t_testKON_lean_pp
t_testKON_fat_pp
t_testKON_total_pp
t_testKON_fatp_pp
```

```{r parra t-test ppm, include=FALSE}
dexa_ppm <- data %>%
select(id, time, group,bmi, wc, lean_mass, fat_mass, total_mass) %>% # velgerrelevante variabler
   mutate(lean_mass_kg = lean_mass/1000) %>%
  mutate(fat_mass_kg = fat_mass/1000) %>%
  mutate(total_mass_kg = total_mass/1000) %>%
  mutate(fatp = fat_mass/total_mass*100) %>%
  select(-lean_mass, -total_mass, -fat_mass) %>%
#Velger variabler
   filter(id != "tr031 10541") %>%
  filter(id != "tr031 11421") %>%
  filter(id != "tr031 13404") %>%
  filter(id != "tr031 004") %>%
  filter(id != "tr031 008") %>%
  filter(id != "tr031 001") %>%
  filter(id != "tr031 016") %>%
  filter(id != "tr031 007") %>%
  filter(id != "tr031 010") %>%
  filter(id != "tr031 012") %>%
  filter(id != "tr031 013") %>%
group_by(time,group) %>% # gruppmerer etter tid og FLS/kontroll 
  print()
   
dexaFLS_ppm <- dexa_ppm %>%
  filter(group != "kon")
  
dexaKON_ppm <- dexa_ppm %>%
  filter(group != "fls")
  
    
#Normalitetssjekk
difFLS_bmi_ppm <- with(dexaFLS_ppm, bmi[time == "pre"] - bmi[time == "post"])
shapiro.test(difFLS_bmi_ppm)

difFLS_wc_ppm <- with(dexaFLS_ppm, wc[time == "pre"] - wc[time == "post"])
shapiro.test(difFLS_wc_ppm)

difFLS_lean_ppm <- with(dexaFLS_ppm, lean_mass_kg[time == "pre"] - lean_mass_kg[time == "post"])
shapiro.test(difFLS_lean_ppm)

difFLS_fat_ppm <- with(dexaFLS_ppm, fat_mass_kg[time == "pre"] - fat_mass_kg[time == "post"])
shapiro.test(difFLS_fat_ppm)

difFLS_total_ppm <- with(dexaFLS_ppm, total_mass_kg[time == "pre"] - total_mass_kg[time == "post"])
shapiro.test(difFLS_total_ppm)

difFLS_fatp_ppm <- with(dexaFLS_ppm, fatp[time == "pre"] - fatp[time == "post"])
shapiro.test(difFLS_fatp_ppm)




difKON_bmi_ppm <- with(dexaKON_ppm, bmi[time == "pre"] - bmi[time == "post"])
shapiro.test(difKON_bmi_ppm)

difKON_wc_ppm <- with(dexaKON_ppm, wc[time == "pre"] - wc[time == "post"])
shapiro.test(difKON_wc_ppm)

difKON_lean_ppm <- with(dexaKON_ppm, lean_mass_kg[time == "pre"] - lean_mass_kg[time == "post"])
shapiro.test(difKON_lean_ppm)

difKON_fat_ppm <- with(dexaKON_ppm, fat_mass_kg[time == "pre"] - fat_mass_kg[time == "post"])
shapiro.test(difKON_fat_ppm)

difKON_total_ppm <- with(dexaKON_ppm, total_mass_kg[time == "pre"] - total_mass_kg[time == "post"])
shapiro.test(difKON_total_ppm)

difKON_fatp_ppm <- with(dexaKON_ppm, fatp[time == "pre"] - fatp[time == "post"])
shapiro.test(difKON_fatp_ppm)

#parret T-test
t_testFLS_bmi_ppm <- t.test(bmi ~ time, data = dexaFLS_ppm, paired = TRUE)
t_testFLS_wc_ppm <- t.test(wc ~ time, data = dexaFLS_ppm, paired = TRUE)
t_testFLS_lean_ppm <- t.test(lean_mass_kg ~ time, data = dexaFLS_ppm, paired = TRUE)
t_testFLS_fat_ppm <- t.test(fat_mass_kg ~ time, data = dexaFLS_ppm, paired = TRUE)
t_testFLS_total_ppm <- t.test(total_mass_kg ~ time, data = dexaFLS_ppm, paired = TRUE)
t_testFLS_fatp_ppm <- t.test(fatp ~ time, data = dexaFLS_ppm, paired = TRUE)



t_testKON_bmi_ppm <- t.test(bmi ~ time, data = dexaKON_ppm, paired = TRUE)
t_testKON_wc_ppm <- t.test(wc ~ time, data = dexaKON_ppm, paired = TRUE)
t_testKON_lean_ppm <- t.test(lean_mass_kg ~ time, data = dexaKON_ppm, paired = TRUE)
t_testKON_fat_ppm <- t.test(fat_mass_kg ~ time, data = dexaKON_ppm, paired = TRUE)
t_testKON_total_ppm <- t.test(total_mass_kg ~ time, data = dexaKON_ppm, paired = TRUE)
t_testKON_fatp_ppm <- t.test(fatp ~ time, data = dexaKON_ppm, paired = TRUE)

t_testFLS_bmi_ppm
t_testFLS_wc_ppm
t_testFLS_lean_ppm
t_testFLS_fat_ppm
t_testFLS_total_ppm
t_testFLS_fatp_ppm


t_testKON_bmi_ppm
t_testKON_wc_ppm
t_testKON_lean_ppm
t_testKON_fat_ppm
t_testKON_total_ppm
t_testKON_fatp_ppm

```

```{r oppsummering, include=FALSE}

t_testFLS_bmi_itt
t_testFLS_wc_itt
t_testFLS_lean_itt
t_testFLS_fat_itt
t_testFLS_total_itt
t_testFLS_fatp_itt

t_testKON_bmi_itt
t_testKON_wc_itt
t_testKON_lean_itt
t_testKON_fat_itt
t_testKON_total_itt
t_testKON_fatp_itt



t_testFLS_bmi_pp
t_testFLS_wc_pp
t_testFLS_lean_pp
t_testFLS_fat_pp
t_testFLS_total_pp
t_testFLS_fatp_pp


t_testKON_bmi_pp
t_testKON_wc_pp
t_testKON_lean_pp
t_testKON_fat_pp
t_testKON_total_pp
t_testKON_fatp_pp



t_testFLS_bmi_ppm
t_testFLS_wc_ppm
t_testFLS_lean_ppm
t_testFLS_fat_ppm
t_testFLS_total_ppm
t_testFLS_fatp_ppm


t_testKON_bmi_ppm
t_testKON_wc_ppm
t_testKON_lean_ppm
t_testKON_fat_ppm
t_testKON_total_ppm
t_testKON_fatp_ppm


```
